version: "3.9"
    
services:
  mysql:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_pass
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
  backend:
    depends_on:
      - mysql
    image: docker.io/library/media-notifier:1.0.0--20220306184632-7b787f811d
    environment:
      - MYSQL_HOST=jdbc:mysql://localhost:3306/test
    ports:
      - "8080:8080"
