name: Default Branch Workflow

on:
  push:
    branches-ignore: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  default:
    uses: ./.github/workflows/build.yml
